Repository serialport/node-serialport, pull requests merged in 2021-09, with the labels that each got.

#2317 Quick low latency fix
  packages/bindings/src/serialport_unix.cpp
Labels: linux, bug

#2298 Automate changelog
  package-lock.json
  package.json
  packages/bindings/package-lock.json
Labels: internal

#2325 Fixed EIO_List to prevent crash when a device has no COM port
  packages/bindings/src/serialport_win.cpp
Labels: windows, bug
